/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 setup.glb --transform 
Files: setup.glb [57.32MB] > D:\Blender files\GLBT Files\New folder\setup-transformed.glb [3.11MB] (95%)
*/

import React, { useRef } from 'react'
import { Html, useGLTF } from '@react-three/drei'

export function Setup(props) {
  const { nodes, materials } = useGLTF('/setup-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.aorus_logotranspa_aorus_logotranspa_0.geometry} material={materials['Material.074_24']} position={[-3.158, 8.63, -3.162]} scale={[0.086, 0.086, 0.091]} />
      <mesh geometry={nodes.BezierCircle_Material104_0.geometry} material={materials.PaletteMaterial001} position={[-0.458, 9.895, -2.826]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.057} />
      <mesh geometry={nodes.bg2_bg2_0.geometry} material={materials['Material.074_29']} position={[-2.871, 8.762, 0.827]} rotation={[1.572, -1.442, 1.567]} scale={1.13} />
      <mesh geometry={nodes['Color-PewDiePie-Logo_Color-PewDiePie-Logo_0'].geometry} material={materials['Material.074_27']} position={[-0.039, 7.278, -0.278]} rotation={[-Math.PI / 2, 0.284, Math.PI / 2]} scale={0.124} />
      <mesh geometry={nodes.Cube004_Material002_0.geometry} material={materials['Material.002']} position={[-2.822, 8.623, 2.989]} rotation={[-Math.PI / 2, -0.07, Math.PI / 2]} scale={[1.676, 0.178, 1.935]} />
      <mesh geometry={nodes.Cube011_Material010_0.geometry} material={materials['Material.074']} position={[-2.194, 8.81, -3.541]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.735, 0.9, 1.573]} />
      <mesh geometry={nodes.Cube015_Material016_0.geometry} material={materials['Material.074_1']} position={[-2.989, 9.054, -4.412]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.894, 0.007, 1.064]} />
      <mesh geometry={nodes.Cube020_Material020_0.geometry} material={materials['Material.074_2']} position={[-2.295, 7.601, -3.638]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.607, 0.739, 0.343]} />
      <mesh geometry={nodes.Cube025_Material023_0.geometry} material={materials['Material.023']} position={[-2.989, 9.054, -4.412]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.894, 0.007, 1.064]} />
      <mesh geometry={nodes.Cube026_Material024_0.geometry} material={materials['Material.024']} position={[-2.989, 9.054, -4.412]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.894, 0.007, 1.064]} />
      <mesh geometry={nodes.Cube027_Material008_0.geometry} material={materials['Material.074_6']} position={[-2.298, 9.522, -4.313]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.015, 0.109, 0.443]} />
      <mesh geometry={nodes.Cube028_Material026_0.geometry} material={materials['Material.074_7']} position={[-2.291, 9.522, -4.328]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.011, 0.097, 0.444]} />
      <mesh geometry={nodes.Cube045_Material027_0.geometry} material={materials['Material.074_8']} position={[-3.456, 7.607, -2.986]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.355, 0.052, 0.206]} />
      <mesh geometry={nodes.Cube048_Material035_0.geometry} material={materials['Material.074_15']} position={[-2.948, 9.495, -3.685]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.174, 0.394, 0.401]} />
      <mesh geometry={nodes.Cube049_Material040_0.geometry} material={materials['Material.074_16']} position={[-2.948, 9.495, -3.685]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.174, 0.394, 0.401]} />
      <mesh geometry={nodes.Cube057_Material059_0.geometry} material={materials['Material.074_22']} position={[-2.606, 8.814, -3.709]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.281, 0.524, 0.127]} />
      <mesh geometry={nodes.Cube058_Material063_0.geometry} material={materials['Material.074_23']} position={[-2.56, 8.95, -3.708]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.333, 0.545, 0.008]} />
      <mesh geometry={nodes.Cube063_Material074_0.geometry} material={materials['Material.074_25']} position={[-0.22, 7.138, -0.278]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.429, 0.429, 0.229]} />
      <mesh geometry={nodes.Cube075_Material086_0.geometry} material={materials['Material.074_26']} position={[-3.914, 8.768, -3.719]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.012, 0.524, 0.177]} />
      <mesh geometry={nodes.Cylinder001_Material028_0.geometry} material={materials['Material.074_11']} position={[-3.026, 7.957, -0.72]} rotation={[-1.571, 1.554, 0]} scale={[0.194, 0.194, 0.025]} />
      <mesh geometry={nodes.Cylinder005_Material041_0.geometry} material={materials['Material.074_17']} position={[-2.946, 9.499, -3.694]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.327, 0.327, 0.342]} />
      <mesh geometry={nodes.Cylinder006_Material050_0.geometry} material={materials['Material.074_19']} position={[-3.429, 8.659, -3.705]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.364, 0.382, 0.106]} />
      <mesh geometry={nodes.Cylinder007_Material051_0.geometry} material={materials['Material.074_20']} position={[-2.579, 8.659, -3.705]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.364, 0.382, 0.106]} />
      <mesh geometry={nodes.gallerymodel_gallerymodel_0.geometry} material={materials['Material.074_28']} position={[-2.755, 8.461, 5.957]} rotation={[0.441, -1.284, 0.441]} scale={0.807} />
      <mesh geometry={nodes['gigabyte-logo_gigabyte-logo_0'].geometry} material={materials['Material.074_31']} position={[-2.95, 11.307, 0.817]} rotation={[1.571, -1.501, 1.571]} scale={0.237} />
      <mesh geometry={nodes.IOSHIELD_IOSHIELD_0.geometry} material={materials['Material.074_3']} position={[-3.931, 9.661, -4.229]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.265, 0.309, 0.318]} />
      <mesh geometry={nodes['maxresdefault_(1)_maxresdefault_(1)_0'].geometry} material={materials['Material.074_10']} position={[-0.457, 7.649, -3.557]} rotation={[0, Math.PI / 2, 0]} scale={0.394} />
      <mesh geometry={nodes['metal-mesh-500x500_metal-mesh-500x500_0'].geometry} material={materials['Material.074_5']} position={[-1.757, 10.383, -3.545]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1, 1.337, 1]} />
      <mesh geometry={nodes.MOBOAORUSORANGETRANS_MOBOAORUSORANGETRANS_0.geometry} material={materials['Material.074_4']} position={[-3.69, 9.69, -4.243]} rotation={[0, 0, 0.651]} scale={0.063} />
      <mesh geometry={nodes.NVIDIA_LOGO_NVIDIA_LOGO_0.geometry} material={materials['Material.074_12']} position={[-1.328, 7.517, -2.894]} scale={0.452} />
      <mesh geometry={nodes.Object_101_Material067_0.geometry} material={materials['Material.074_36']} position={[0.143, 7.139, 4.027]} rotation={[-Math.PI / 2, -1.481, Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_103_Material070_0.geometry} material={materials['Material.074_39']} position={[0.143, 7.139, 4.027]} rotation={[-Math.PI / 2, -1.481, Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_105_Tasten_2_0.geometry} material={materials.Tasten_2} position={[0.143, 7.139, 4.027]} rotation={[-Math.PI / 2, -1.481, Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_109_Material069_0.geometry} material={materials['Material.074_38']} position={[0.143, 7.139, 4.027]} rotation={[-Math.PI / 2, -1.481, Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_113_Material068_0.geometry} material={materials['Material.074_37']} position={[0.143, 7.139, 4.027]} rotation={[-Math.PI / 2, -1.481, Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_115_Material057_0.geometry} material={materials['Material.074_33']} position={[0.143, 7.139, 4.027]} rotation={[-Math.PI / 2, -1.481, Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_121_Material066_0.geometry} material={materials['Material.074_35']} position={[0.143, 7.139, 4.027]} rotation={[-Math.PI / 2, -1.481, Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_131_Material060_0.geometry} material={materials['Material.074_34']} position={[0.143, 7.139, 4.027]} rotation={[-Math.PI / 2, -1.481, Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes.Object_137_Material005_0.geometry} material={materials['Material.074_32']} position={[0.143, 7.139, 4.027]} rotation={[-Math.PI / 2, -1.481, Math.PI / 2]} scale={0.914} />
      <mesh geometry={nodes['Object_782_OnTheFly-bg_0'].geometry} material={materials['Material.074_40']} position={[-0.318, 7.219, 2.436]} rotation={[-Math.PI / 2, 0.078, Math.PI / 2]} scale={0.219} />
      <mesh geometry={nodes.Plane_Material053_0.geometry} material={materials['Material.074_21']} position={[-0.162, 7.069, -0.295]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.244, 1.541, 1.199]} />
      <mesh geometry={nodes.psuback_psuback_0.geometry} material={materials['Material.074_13']} position={[-3.937, 7.593, -3.531]} rotation={[0, Math.PI / 2, 0]} scale={0.595} />
      <mesh geometry={nodes['rgb-hdd-cover-aorus-v1_rgb-hdd-cover-aorus-v1_0'].geometry} material={materials['Material.074_9']} position={[-2.269, 7.645, -2.892]} scale={0.369} />
      <mesh geometry={nodes['test-aorus-m2-souris-aorus-rgb2_test-aorus-m2-souris-aorus-rgb2'].geometry} material={materials['Material.074_18']} position={[-2.493, 8.32, -4.356]} scale={0.352} />
      <mesh geometry={nodes.usb_usb_0.geometry} material={materials['Material.074_14']} position={[-0.629, 10.384, -2.901]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.073} />
      <mesh geometry={nodes.defaultMaterial005.geometry} material={materials.standardSurface1} position={[7.896, 3.117, -2.479]} rotation={[-Math.PI / 2, 0, -1.099]} scale={[0.121, 0.121, 0.143]} />
      <mesh geometry={nodes.Material2.geometry} material={materials.Brick_Antique_02} position={[-0.385, 0.636, -7.881]} rotation={[-Math.PI / 2, 0, 0]} scale={0.114} />
      <mesh geometry={nodes.Material2001.geometry} material={materials.material} position={[-0.385, 0.636, -7.881]} rotation={[-Math.PI / 2, 0, 0]} scale={0.114} />
      <mesh geometry={nodes.Material2002.geometry} material={materials.material_1} position={[-0.385, 0.636, -7.881]} rotation={[-Math.PI / 2, 0, 0]} scale={0.114} />
      <mesh geometry={nodes.Material2003.geometry} material={materials.PaletteMaterial002} position={[-0.385, 0.636, -7.881]} rotation={[-Math.PI / 2, 0, 0]} scale={0.114} />
      <mesh geometry={nodes.Material2010.geometry} material={materials.LightYellow} position={[-0.385, 0.636, -7.881]} rotation={[-Math.PI / 2, 0, 0]} scale={0.114} />
      <instancedMesh args={[nodes.aorus_case_fans_aorus_case_fans_0.geometry, materials['Material.074_0'], 10]} instanceMatrix={nodes.aorus_case_fans_aorus_case_fans_0.instanceMatrix} />
      <instancedMesh args={[nodes.Cube_Material_0.geometry, materials['Material.001'], 5]} instanceMatrix={nodes.Cube_Material_0.instanceMatrix} />
      <instancedMesh args={[nodes.Cube016_Material017_0.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.Cube016_Material017_0.instanceMatrix} />
      <instancedMesh args={[nodes.Cube033_Material025_0.geometry, materials.PaletteMaterial001, 10]} instanceMatrix={nodes.Cube033_Material025_0.instanceMatrix} />
      <instancedMesh args={[nodes.Object_784_Material057_0.geometry, materials['Material.074_33'], 6]} instanceMatrix={nodes.Object_784_Material057_0.instanceMatrix} />
      <instancedMesh args={[nodes.Object_974_Material057_0.geometry, materials['Material.074_33'], 7]} instanceMatrix={nodes.Object_974_Material057_0.instanceMatrix} />
      <instancedMesh args={[nodes.Object_976_Material070_0.geometry, materials['Material.074_39'], 6]} instanceMatrix={nodes.Object_976_Material070_0.instanceMatrix} />
      <Html
              wrapperClass='pc'
              position={[-4.1, 9.5, -2.7]}
              distanceFactor={1.10}
              transform
              rotation={[0, Math.PI / 2, 0]} 
              rotation-x={-0.01}
            >
           
            
              <iframe src='https://3-d-portfolio-liard-five.vercel.app/' />
            </Html>
    </group>
  )
}

useGLTF.preload('/setup-transformed.glb')
